# Generated by Django 3.0.3 on 2020-02-23 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='favicon',
            field=models.FileField(blank=True, help_text='Icon size can be max 512x512', null=True, upload_to='', verbose_name='Site favicon'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='site_logo',
            field=models.FileField(blank=True, help_text='Logo size max ...', null=True, upload_to='', verbose_name='Site Logo'),
        ),
    ]
