# Generated by Django 3.0.3 on 2020-03-15 22:14

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPostCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Uncategorized', max_length=25, unique=True, verbose_name='Blog Post Category')),
            ],
            options={
                'verbose_name': 'Blog Post Category',
                'verbose_name_plural': 'Blog Post Categories',
            },
        ),
        migrations.CreateModel(
            name='BlogPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Published Date')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Blog Post Title')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Featured Image')),
                ('blog_keywords', models.CharField(max_length=255, verbose_name='Blog Post Meta Keywords')),
                ('blog_description', ckeditor.fields.RichTextField()),
                ('summary', models.CharField(blank=True, editable=False, max_length=200, null=True, verbose_name='Blog Post Summary')),
                ('category', models.ManyToManyField(to='blog.BlogPostCategories')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-created_at', 'title'],
            },
        ),
    ]
