# Generated by Django 3.0.3 on 2020-03-17 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposts',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Featured Image'),
        ),
    ]
