# Generated by Django 3.0.3 on 2020-03-18 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200318_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogposts',
            name='view',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
