# Generated by Django 3.0.3 on 2020-02-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Home Full Name')),
                ('job_desc', models.TextField(default='', verbose_name='Job Description')),
                ('home_title_1', models.TextField(default='', verbose_name='Home Title 1')),
                ('home_title_2', models.TextField(default='', verbose_name='Home Title 2')),
                ('home_title_3', models.TextField(default='', verbose_name='Home Title 3')),
                ('home_bg', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Home Backgroud IMG')),
            ],
            options={
                'verbose_name': 'Home Page Setting',
                'verbose_name_plural': 'Home page Settings',
            },
        ),
    ]
