# Generated by Django 3.0.3 on 2020-03-13 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='location',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Location'),
        ),
    ]
