# Generated by Django 3.0.3 on 2020-03-20 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='icon',
            field=models.ImageField(blank=True, help_text='for PDF', null=True, upload_to='', verbose_name='Social Media Icon'),
        ),
    ]
