# Generated by Django 3.0.3 on 2020-02-27 11:38

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='Uncategorized', max_length=25, verbose_name='Portfolio Category')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Protfolio Title One')),
                ('title_two', models.CharField(blank=True, max_length=255, null=True, verbose_name='Portfolio Title Two')),
                ('portfolio_type', models.CharField(choices=[('Text', 'text'), ('Video', 'video'), ('Image', 'image'), ('Gallery', 'gallery')], max_length=15, verbose_name='Portfolio Type')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Featured Image')),
                ('portfolio_video', models.URLField(blank=True, null=True, verbose_name='Video Link')),
                ('portfolio_keywords', models.CharField(max_length=255, verbose_name='Portfolio Meta Keywords')),
                ('portfolio_description', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
