# Generated by Django 3.0.3 on 2020-03-15 22:14

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Uncategorized', max_length=25, unique=True, verbose_name='Portfolio Category')),
            ],
            options={
                'verbose_name': 'Portfolio Category',
                'verbose_name_plural': 'Protfolio Categories',
            },
        ),
        migrations.CreateModel(
            name='Techs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Uncategorized', max_length=25, unique=True, verbose_name='Technology')),
            ],
            options={
                'verbose_name': 'Tech',
                'verbose_name_plural': 'Techs',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Published Date')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Protfolio Title One')),
                ('title_two', models.CharField(blank=True, max_length=255, null=True, verbose_name='Portfolio Title Two')),
                ('portfolio_type', models.CharField(choices=[('Text', 'text'), ('Video', 'video'), ('Image', 'image'), ('Gallery', 'gallery')], max_length=15, verbose_name='Portfolio Type')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Featured Image')),
                ('portfolio_video', models.URLField(blank=True, null=True, verbose_name='Video Link')),
                ('portfolio_keywords', models.CharField(max_length=255, verbose_name='Portfolio Meta Keywords')),
                ('portfolio_description', ckeditor.fields.RichTextField()),
                ('client', models.CharField(blank=True, max_length=255, null='True', verbose_name='Client')),
                ('project_web', models.URLField(blank=True, null=True, verbose_name='Project URL')),
                ('summary', models.CharField(blank=True, editable=False, max_length=200, null=True, verbose_name='Duyuru Özet')),
                ('category', models.ManyToManyField(to='portfolio.PortfolioCategories')),
                ('techs', models.ManyToManyField(to='portfolio.Techs')),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolios',
                'ordering': ['-created_at', 'title'],
            },
        ),
    ]
