# Generated by Django 3.0.3 on 2020-02-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name': 'Portfolio', 'verbose_name_plural': 'Portfolios'},
        ),
        migrations.AddField(
            model_name='portfolio',
            name='summary',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True, verbose_name='Duyuru Özet'),
        ),
    ]
