# Generated by Django 3.0.3 on 2020-03-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20200227_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Uncategorized', max_length=25, verbose_name='Portfolio Category')),
            ],
            options={
                'verbose_name': 'Portfolio Category',
                'verbose_name_plural': 'Protfolio Categories',
            },
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='category',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='category',
            field=models.ManyToManyField(to='portfolio.PortfolioCategories'),
        ),
    ]
