# Generated by Django 3.0.3 on 2020-03-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20200305_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliocategories',
            name='title',
            field=models.CharField(default='Uncategorized', max_length=25, unique=True, verbose_name='Portfolio Category'),
        ),
    ]
