# Generated by Django 3.0.3 on 2020-03-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20200305_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Techs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Uncategorized', max_length=25, unique=True, verbose_name='Portfolio Category')),
            ],
            options={
                'verbose_name': 'Tech',
                'verbose_name_plural': 'Techs',
            },
        ),
        migrations.AddField(
            model_name='portfolio',
            name='client',
            field=models.CharField(blank=True, max_length=255, null='True', verbose_name='Client'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='project_web',
            field=models.URLField(blank=True, null=True, verbose_name='Project URL'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='techs',
            field=models.ManyToManyField(to='portfolio.Techs'),
        ),
    ]
