# Generated by Django 3.0.3 on 2020-03-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20200305_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techs',
            name='title',
            field=models.CharField(default='Uncategorized', max_length=25, unique=True, verbose_name='Technology'),
        ),
    ]
