# Generated by Django 3.0.3 on 2020-03-13 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_portfolio_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['-created_at', 'title'], 'verbose_name': 'Portfolio', 'verbose_name_plural': 'Portfolios'},
        ),
    ]
