# Generated by Django 3.0.3 on 2020-03-15 22:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Educations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('finish_date', models.DateField(blank=True, help_text='If this field is left blank, it means that you are still studying.', null=True, verbose_name='Finish Date')),
                ('institute_name', models.CharField(max_length=255, verbose_name='Institute Name')),
                ('institute_stage', models.CharField(max_length=255, verbose_name='Institute Stage')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Educations',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Employments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('finish_date', models.DateField(blank=True, help_text='If this field is left blank, it means that you are still working this corporate.', null=True, verbose_name='Finish Date')),
                ('co_name', models.CharField(max_length=255, verbose_name='Corporate Name')),
                ('job_title', models.CharField(max_length=255, verbose_name='Job Title')),
                ('job_description', models.CharField(max_length=255, verbose_name='Job Description')),
            ],
            options={
                'verbose_name': 'Employment',
                'verbose_name_plural': 'Employments',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Skill Title')),
                ('progress', models.PositiveIntegerField(help_text='Max Value = 100, Min Value= 1', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Skill Percent')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
            },
        ),
    ]
