# Generated by Django 3.0.3 on 2020-03-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educations',
            name='finish_date',
            field=models.DateField(auto_now_add=True, verbose_name='Finish Date'),
        ),
    ]
