# Generated by Django 3.0.3 on 2020-03-13 21:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0002_auto_20200314_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educations',
            name='finish_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 13, 21, 15, 44, 415790, tzinfo=utc), verbose_name='Finish Date'),
        ),
    ]
