# Generated by Django 3.0.3 on 2020-03-13 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0005_auto_20200314_0018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employments',
            options={'ordering': ['-start_date'], 'verbose_name': 'Employment', 'verbose_name_plural': 'Employments'},
        ),
    ]
