# Generated by Django 3.0.3 on 2020-03-13 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0006_auto_20200314_0031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educations',
            options={'ordering': ['-start_date'], 'verbose_name': 'Education', 'verbose_name_plural': 'Educations'},
        ),
    ]
